### ISSUE TITLE
funetuning error

### ISSUE THREAD

**Issue by praveenkumar-ctrl** [SuperSupermoon/MedViLL#10]
sir i am getting this error while funetuning Medical Visual Qestion Answering Example
Traceback (most recent call last):
  File "finetune.py", line 476, in <module>
    main()
  File "finetune.py", line 411, in main
    for step, batch in enumerate(iter_bar):
  File "/home/cse/ckm/py37/lib/python3.7/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/home/cse/ckm/py37/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 644, in __next__
    data = self._next_data()
  File "/home/cse/ckm/py37/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1337, in _next_data
    return self._process_data(data)
  File "/home/cse/ckm/py37/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1363, in _process_data
    data.reraise()
  File "/home/cse/ckm/py37/lib/python3.7/site-packages/torch/_utils.py", line 475, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/cse/ckm/py37/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/cse/ckm/py37/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    return self.collate_fn(data)
  File "/home/cse/ckm/code/seelam/code/MedViLL/downstream_task/report_generation_and_vqa/loader_utils.py", line 23, in batch_list_to_batch_tensors
    batch_tensors.append(torch.stack(x))
RuntimeError: stack expects each tensor to be equal size, but got [3, 434, 329] at entry 0 and [3, 642, 1024] at entry 1

can you please check it

**Comment by SuperSupermoon** [comment]
Hello, praveenkumar-ctrl!

We fixed some bugs for the medical VQA task.

Could you please try again?
If there are still problems, please leave a new issue.

Thanks!
